name: fractopo

channels:
  - conda-forge

# Changes here should be kept in sync with ./pyproject.toml
dependencies:
  - python >=3.10,<3.15
  - click
  - geopandas >=1.00.0
  - matplotlib-base
  - numpy
  - pandas >=1.3,<3.0.0
  - powerlaw
  - python-ternary
  - rich
  - scikit-learn
  - scipy
  - seaborn
  - shapely >=2.0.0,<3.0.0
  - typer
  - joblib
  - beartype
  # Dependencies for testing
  - hypothesis
  - pytest
  - pytest-regressions
  - marimo
