name: fractopo

channels:
  - conda-forge

# Changes here should be kept in sync with ./pyproject.toml
dependencies:
  - python >=3.8,<3.12
  - click
  - geopandas >=0.11.1
  - matplotlib-base
  - numpy
  - pandas >=1.3,<3.0.0
  - powerlaw
  - pygeos >=0.13.0
  - python-ternary
  - rich
  - scikit-learn
  - scipy
  - seaborn
  - shapely >=2.0.0,<3.0.0
  - typer
  - joblib
  # Dependencies for testing
  - hypothesis
  - pytest
  - pytest-regressions
