name: fractopo

channels:
  - conda-forge

# Changes here should be kept in sync with ./pyproject.toml
dependencies:
  - python >=3.8,<3.12
  - click
  - geopandas >=0.11.1,<0.12
  - matplotlib-base
  - numpy
  - pandas >=1.3,<1.4
  - powerlaw
  - pygeos >=0.13.0,<0.14.0
  - python-ternary
  - rich >=11.0.0,<11.1.0
  - scikit-learn
  - scipy
  - seaborn
  - shapely >=1.8.0,<1.9.0
  - typer >=0.4.0,<0.5.0
  - joblib >=1.2.0,<1.3.0
  # Dependencies for testing
  - hypothesis
  - pytest
  - pytest-regressions=2.2.0
