name: test

on: [push, pull_request]

jobs:
  # Test
  pytest-and-coverage:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox invoke
      - name: Test with invoke -> nox -> pytest
        run: invoke ci-test

  build-n-publish:
    needs: pytest-and-coverage
    name: Build and publish Python ðŸ distributions ðŸ“¦ to TestPyPI and PyPI
    # Pushes to TestPyPI on all pushes of master branch
    # Pushes to PyPI on tagged commit pushes of master branch
    # Additionally tests building with setuptools on all branches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install setuptools, wheel, invoke and nox
        run: >-
          python -m pip install setuptools wheel invoke nox
      - name: Update requirements with nox session
        run: >-
          invoke requirements
      - name: Build binary wheel and a source tarball
        run: >-
          python setup.py sdist bdist_wheel
      - name: Publish distribution ðŸ“¦ to TestPyPI on pushes
        # Publish to TestPyPI on all pushes on master branch
        if: github.event_name == 'push' || github.ref == 'refs/heads/master'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution ðŸ“¦ to PyPI on tagged commit pushes
        # Publish to PyPI on tagged commit pushes
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
